<a href="https://colab.research.google.com/github/JohnNach123/Fromzero/blob/master/pima.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [0]:
columns = ["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age"]
labels = df["Outcome"].values
features = df[list(columns)].values

In [0]:
columns


['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [0]:
labels


array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [0]:
features

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(features,labels,test_size=0.30)
clf = RandomForestClassifier (n_estimators=1)
clf = clf.fit(X_train,y_train)

accuracy = clf.score(X_train,y_train)
accuracy

0.8603351955307262

In [0]:
clf = RandomForestClassifier (n_estimators=1)
clf = clf.fit(X_train,y_train)

accuracy = clf.score(X_test,y_test)
accuracy

0.670995670995671

# confusion matrix and classification report

In [0]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
ypredict = clf.predict(X_train)
print(classification_report(y_train,ypredict))

              precision    recall  f1-score   support

           0       0.93      0.90      0.92       342
           1       0.83      0.88      0.86       195

    accuracy                           0.89       537
   macro avg       0.88      0.89      0.89       537
weighted avg       0.90      0.89      0.89       537



In [0]:
print(confusion_matrix(y_train,ypredict))

[[308  34]
 [ 23 172]]


In [0]:
ypredict = clf.predict(X_test)
print(classification_report(y_test,ypredict))
print(confusion_matrix(y_test,ypredict))

              precision    recall  f1-score   support

           0       0.76      0.76      0.76       158
           1       0.48      0.48      0.48        73

    accuracy                           0.67       231
   macro avg       0.62      0.62      0.62       231
weighted avg       0.67      0.67      0.67       231

[[120  38]
 [ 38  35]]


# data normalization/standardization : standard scaler , Min-Max scaler

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()            # scaler = preprocessing.StandarScaler
scaler.fit(X_train)                  # fit only on training data.
X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)    # make same transformation on testing data.


In [0]:
clf = RandomForestClassifier (n_estimators=1)
clf = clf.fit(X_train,y_train)

accuracy = clf.score(X_train,y_train)
print(accuracy)
clf = RandomForestClassifier (n_estimators=1)
clf = clf.fit(X_train,y_train)

accuracy = clf.score(X_test,y_test)
print(accuracy)
ypredict = clf.predict(X_train)
print(classification_report(y_train,ypredict))
print(confusion_matrix(y_train,ypredict))
ypredict = clf.predict(X_test)
print(classification_report(y_test,ypredict))
print(confusion_matrix(y_test,ypredict))

0.8733705772811918
0.683982683982684
              precision    recall  f1-score   support

           0       0.89      0.91      0.90       342
           1       0.83      0.79      0.81       195

    accuracy                           0.87       537
   macro avg       0.86      0.85      0.86       537
weighted avg       0.87      0.87      0.87       537

[[311  31]
 [ 40 155]]
              precision    recall  f1-score   support

           0       0.76      0.78      0.77       158
           1       0.50      0.48      0.49        73

    accuracy                           0.68       231
   macro avg       0.63      0.63      0.63       231
weighted avg       0.68      0.68      0.68       231

[[123  35]
 [ 38  35]]


# the end is the standardscaler is not performant for the classifier

In [0]:
from sklearn.preprocessing import Min.MaxScaler
scaler = Min-MaxScaler()            # scaler = preprocessing.Min-MaxScaler.
scaler.fit(X_train)                  # fit only on training data.
X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)    # make same transformation on testing data.


In [0]:
clf = RandomForestClassifier (n_estimators=1)
clf = clf.fit(X_train,y_train)

accuracy = clf.score(X_train,y_train)
print(accuracy)
clf = RandomForestClassifier (n_estimators=1)
clf = clf.fit(X_train,y_train)

accuracy = clf.score(X_test,y_test)
print(accuracy)
ypredict = clf.predict(X_train)
print(classification_report(y_train,ypredict))
print(confusion_matrix(y_train,ypredict))
ypredict = clf.predict(X_test)
print(classification_report(y_test,ypredict))
print(confusion_matrix(y_test,ypredict))

0.8603351955307262
0.6536796536796536
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       342
           1       0.84      0.84      0.84       195

    accuracy                           0.88       537
   macro avg       0.88      0.88      0.88       537
weighted avg       0.88      0.88      0.88       537

[[311  31]
 [ 31 164]]
              precision    recall  f1-score   support

           0       0.76      0.72      0.74       158
           1       0.46      0.52      0.49        73

    accuracy                           0.65       231
   macro avg       0.61      0.62      0.61       231
weighted avg       0.67      0.65      0.66       231

[[113  45]
 [ 35  38]]


# the result is the data standardization/normalization is not performant for classifier